name: Build Electron App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            packageType: zip
            target: darwin
          - os: windows-latest
            packageType: nsis
            target: win32
          - os: ubuntu-latest
            packageType: deb
            target: linux
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.4
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: npm ci
      - name: Build Electron App
        run: npm run build:${{ matrix.target }}
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: out/make/${{ matrix.target }}/${{ matrix.packageType }}
