name: Build Electron App with Forge

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm install
        npm install --save-dev @electron-forge/cli

    - name: Build Electron app
      run: npx electron-forge make --platform ${{ matrix.os }} --arch x64

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-build
        path: out/make/*

    - name: Create DEB package
      run: npx electron-installer-debian --src out/make/* --dest out/installers/ --arch amd64

    - name: Create RPM package
      run: npx electron-installer-redhat --src out/make/* --dest out/installers/ --arch x86_64
