name: Node.js CI

on:
  push:
    branches: 
      - main
      - Thomas
      - Gabriel
      - Alexis
      - Alexis2
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
    - name: Cache
      uses: actions/cache@v2.1.8
      with:
          path: |
              ~/.pnpm-store
              node_modules
              */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
              ${{ runner.os }}-
          run-id: ${{ github.run_id }}
      env:
          PNPM_STORE_DIR: ~/.pnpm-store
          PNPM_REGISTRY: https://registry.npmjs.org/
          PNPM_UPDATE: true
    - run: npm install -g pnpm
    - run: pnpm install
    - run: pnpm run test
