name: Node.js CI

on:
  push:
    branches: 
      - main
      - Thomas
      - Gabriel
      - Alexis
      - Alexis2
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
    - name: Cache
      uses: actions/cache@v2.1.8
      with:
          path: |
              node_modules
              */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
    - run: npm install
    - run: npm ci    

    - run: npm run test
